---
abstract: 'Convert data to/from the PGP word list'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  List::Util: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132620'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PGP-Words-Tiny
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  PGP::Words::Tiny:
    file: lib/PGP/Words/Tiny.pm
    version: 0.002
requires:
  Carp: 0
  Exporter: 5.57
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/PGP-Words-Tiny/issues
  homepage: https://github.com/dagolden/PGP-Words-Tiny
  repository: https://github.com/dagolden/PGP-Words-Tiny.git
version: 0.002
x_authority: cpan:DAGOLDEN
