---
abstract: 'Convert data to/from the PGP word list'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PGP-Words-Tiny
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  PGP::Words::Tiny:
    file: lib/PGP/Words/Tiny.pm
    version: 0.001
requires:
  Carp: 0
  Exporter: 5.57
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com//pgp-words-tiny/issues
  homepage: https://metacpan.org/release/PGP-Words-Tiny
  repository: git://github.com/dagolden/pgp-words-tiny.git
version: 0.001
